sudo: false
language: java
script:
  - cd antlr4
  - mvn verify -Dantlr.testinprocess=true -DJDK_SOURCE_ROOT=../runtime/Java/src -Dperformance.package=
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
